[package]
name = "num_reader"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "num_reader"
path = "src/num_reader.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "^0.2.14"